# Generated by Django 4.2.19 on 2025-03-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_app_admin',
            field=models.BooleanField(default=False, verbose_name='Hat Zugriff auf Admin-View'),
        ),
    ]
