# Generated by Django 3.2.19 on 2025-03-09 14:49
<<<<<<< HEAD
=======
# Generated by Django 4.2.19 on 2025-03-01 21:04
>>>>>>> 57f056b (adminview_first)
=======
>>>>>>> ffdd6c1 (adminview user-list added, editing possible)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('grund', models.TextField()),
                ('klasse', models.CharField(max_length=100)),
<<<<<<< HEAD
=======
                ('title', models.CharField(max_length=100)),
                ('grund', models.TextField()),
>>>>>>> 57f056b (adminview_first)
=======
>>>>>>> ffdd6c1 (adminview user-list added, editing possible)
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('anfangsdatum', models.DateField()),
                ('enddatum', models.DateField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='in_progress', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('unterricht', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('response', models.CharField(choices=[('not_responded', 'Noch nicht geantwortet'), ('accepted', 'Genehmigt'), ('declined', 'Abgelehnt')], default='not_responded', max_length=100)),
                ('reason', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('antrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antraege.antrag')),
            ],
        ),
    ]
