# Generated by Django 4.2.19 on 2025-03-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antraege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfrage',
            name='is_principle',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
