# Generated by Django 4.2.19 on 2025-04-10 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antraege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='schueler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antrag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anfrage',
            name='antrag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antraege.antrag'),
        ),
    ]
