# Generated by Django 4.2.19 on 2025-04-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antraege', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lehrer',
            name='principal',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='lehrer',
            name='secretariat',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
