# Generated by Django 4.2.19 on 2025-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antraege', '0002_anfrage_is_principle'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfrage',
            name='gm',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='anfrage',
            name='im',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
