# Generated by Django 4.2.19 on 2025-04-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antraege', '0003_lehrer_principal_lehrer_secretariat'),
        ('antraege', '0003_lehrer_principal_lehrer_secretariat 2'),
    ]

    operations = [
    ]
