# Generated by Django 4.2.19 on 2025-04-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antraege', '0003_anfrage_gm_anfrage_im'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kuerzel', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lehrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
