# Generated by Django 4.2.19 on 2025-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antraege', '0004_fach_lehrer_zaehler'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='temp',
            field=models.IntegerField(default=0),
        ),
    ]
