# Generated by Django 4.2.19 on 2025-05-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antraege', '0004_merge_20250426_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrag',
            name='eltern_bestaetigung',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antrag',
            name='eltern_notwendig',
            field=models.BooleanField(default=False),
        ),
    ]
