# Generated by Django 4.2.19 on 2025-04-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antraege', '0005_zaehler_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrag',
            name='klasse',
            field=models.CharField(choices=[('7', '7'), ('8', '8'), ('9a', '9a'), ('9b', '9b'), ('9c', '9c'), ('10a', '10a'), ('10b', '10b'), ('10c', '10c'), ('11', '11'), ('12', '12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='titel',
            field=models.CharField(max_length=50),
        ),
    ]
